import Head from 'next/head'
import Image from 'next/image'
import EventList from '../components/events/event-list'
import {getFeaturedEvents} from '../utils/fetcher'

export default function Home({events}) {
  return (
    <div>
      <Head>
        <title>Next-Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-2xl py-8 mx-auto space-y-8 rounded-xl ">
        <EventList lists={events} />
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const events = await getFeaturedEvents()

  return {
    props: {events},
  }
}
