import Head from 'next/head'
import Image from 'next/image'
import {getFeaturedEvents} from '../utils/fetcher'

export default function Home({events}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" px-auto max-w-xl mx-auto my-20 ">
        {events.map(event => (
          <div
            key={event.id}
            className="md:flex md:justify-center space-x-2 bg-slate-900 shadow-md rounded-md space-y-2 mb-6"
          >
            <Image
              src={event.image}
              alt={event.id}
              width={200}
              height={140}
              priority={true}
              className="rounded-r-none rounded-l-md sm:p-0"
              style={{width: 'auto', height: 'auto'}}
            />
            <div className="">
              <h1 className="p-2 text-blue-200 text-2xl">{event.title}</h1>
              <h2 className="p-2 text-white text-lg ">{event.date}</h2>
              <p className="pb-2 text-slate-300 mb-2">{event.description}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const events = await getFeaturedEvents()

  return {
    props: {events},
  }
}
